name: GNOME Sudoku AppImage CI
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:41
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf install -y --skip-unavailable \
            gcc gcc-c++ make cmake ninja-build pkgconf-pkg-config wget git m4 vala \
            libgee-devel json-glib-devel qqwing-devel yelp-tools itstool gettext \
            libxml2-devel desktop-file-utils gobject-introspection-devel glib2-devel \
            pango-devel cairo-devel gdk-pixbuf2-devel libepoxy-devel graphene-devel \
            wayland-devel libX11-devel libxkbcommon-devel vulkan-loader-devel \
            libffi-devel zlib-devel libmount-devel libselinux-devel pcre2-devel \
            python3-devel dbus-devel python3-gobject python3-pip file \
            fribidi-devel fontconfig-devel sqlite-devel cups-devel \
            colord-devel lcms2-devel rest-devel libsoup3-devel \
            libcloudproviders-devel libadwaita-devel gtk4-devel
          pip3 install meson
      - name: Build Dependencies
        run: |
          python3 -m venv venv_build
          ./venv_build/bin/pip install meson ninja
          bash build_deps.sh
      - name: Build
        run: bash build/build-gnome-sudoku-appimage.sh
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sudoku-AppImage
          path: "*.AppImage"

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: Sudoku-AppImage
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
          files: "*.AppImage"
          generate_release_notes: true
          draft: true
          prerelease: ${{ github.ref_name == 'main' }}
          make_latest: ${{ github.ref_name != 'main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
